name: iiplanner
description: A new daily planner app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.25.0
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12+1
  google_sign_in: ^4.5.9
  extension_google_sign_in_as_googleapis_auth: ^1.0.4
  url_launcher: ^5.7.10
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_remote_config: ^0.6.0
  firebase_auth: ^0.20.0+1
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
