name: iiplanner
description: A new daily planner app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12+1
  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
